site_name: Semester notes
theme:
    name: material
    palette:
        scheme: slate
        primary: teal
        accent: purple
    features:
        - navigation.tabs
plugins:
    - search
    - glightbox
markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
          use_pygments: true
          auto_title: true
    - pymdownx.arithmatex:
          generic: true
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - def_list
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tasklist:
          custom_checkbox: true

extra:
    generator: false

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
