site_name: Semester notes
theme:
    name: material
    palette:
        scheme: slate
        primary: teal
        accent: purple
    features:
        - navigation.tabs
plugins:
    - search
    - glightbox
markdown_extensions:
<<<<<<< HEAD
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
=======
    - pymdownx.highlight:
          anchor_linenums: true
          use_pygments: true
          auto_title: true
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - def_list
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tasklist:
          custom_checkbox: true

extra:
    generator: false
>>>>>>> 9ef7eff6693071e17c1fbf9affe6fbe59f0c61d6
