site_name: Security Notes
theme:
    name: material
    palette:
        scheme: slate
        primary: teal
        accent: purple
    features:
        - navigation.tabs
        - content.code.copy
plugins:
    - search
    - glightbox
markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
          use_pygments: true
          auto_title: true
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - def_list
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tasklist:
          custom_checkbox: true

extra:
    generator: false
