services:
  nginx:
    container_name: nginx
    build: ./nginx/
    ports:
      - 80:80
    volumes:
        - ./src/:/var/www/html/

  php:
    container_name: php
    build: ./src/
    expose:
      - 9000
    volumes:
      - ./src/:/var/www/html/

  ssh:
    container_name: ssh-user-space
    build: ./ssh/
    ports:
      - 2222:22
    volumes:
      - ./ssh/home:/home/

  vsftpd:
    image: fauria/vsftpd
    container_name: ftp-server
    environment:
      FTP_USER: "anonymous"
      FTP_PASS: "anonymous"
      PASV_ADDR_RESOLVE: "YES"
    ports:
      - 20:20
      - 21:21
    volumes:
      - ./ftp/pub:/home/vsftpd
      - /var/log/ftp:/var/log/vsftpd
