services:
  nginx:
    container_name: nginx
    build: ./nginx/
    ports:
      - 80:80
    volumes:
        - ./web-server/src/:/var/www/html/

  php:
    container_name: php
    build: ./web-server/
    expose:
      - 9000
    volumes:
      - ./web-server/src/:/var/www/html/

  ssh:
    container_name: ssh-user-space
    build: ./ssh/
    ports:
      - 2222:22

  ftp:
    build: ./ftp/
    ports:
      - "20:20"
      - "21:21"
    volumes:
      - ./ftp/pub:/home/ftpusers

  # vsftpd:
  #   image: fauria/vsftpd
  #   container_name: ftp-server
  #   environment:
  #     FTP_ANONYMOUS: "true"
  #     PASV_ADDR_RESOLVE: "YES"
  #   ports:
  #     - 20:20
  #     - 21:21
  #   volumes:
  #     - ./ftp/pub:/var/vsftpd
  #     - /var/log/ftp:/var/log/vsftpd
